# app/dashboard.py

import os
import sys
import subprocess

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
from Bio import SeqIO

# Allow imports from project root
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

# =====================================================================
# PAGE CONFIG
# =====================================================================
st.set_page_config(
    page_title="eTraceAI",
    page_icon="🧬",
    layout="wide"
)

# =====================================================================
# CUSTOM CSS
# =====================================================================
st.markdown("""
<style>
body { font-family: 'Segoe UI', sans-serif; }
.sidebar .sidebar-content { background-color: #f3f6f9; }
.main-title { font-size: 42px; font-weight: 700; color: #2E7D32; }
.subtitle { font-size: 18px; color: #555; margin-top: -12px; }
.section-title { font-size: 26px; font-weight: 600; margin-top: 15px; color: #1B5E20; }
.card {
    background-color: #f7f9fc; padding: 20px; border-radius: 10px;
    border: 1px solid #e6e6e6; margin-bottom: 20px;
}
.footer {
    text-align:center; color:#777; margin-top:40px;
    padding: 15px; font-size:14px;
}
</style>
""", unsafe_allow_html=True)

# Hide Streamlit chrome
st.markdown("""
<style>
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}
</style>
""", unsafe_allow_html=True)

# =====================================================================
# NAVIGATION
# =====================================================================
nav_options = ["Home", "Results", "Visualizations", "FASTA Preview", "Developer Info"]
page = st.selectbox("📂 Navigate", nav_options)
st.markdown("<br>", unsafe_allow_html=True)

# =====================================================================
# PATHS
# =====================================================================
UPLOAD_PATH = "data/sample1.fasta"
RESULT_CSV = "output/match_results.csv"
EMB_PATH = "output/dbn_embeddings.npy"

# Multi-level taxonomy images generated by phylum_barplot.py
TAXON_IMAGES = {
    "Phylum": ("output/phylum_barplot_total.png", "output/phylum_barplot_novel.png"),
    "Class": ("output/class_barplot_total.png", "output/class_barplot_novel.png"),
    "Order": ("output/order_barplot_total.png", "output/order_barplot_novel.png"),
    "Family": ("output/family_barplot_total.png", "output/family_barplot_novel.png"),
    "Genus": ("output/genus_barplot_total.png", "output/genus_barplot_novel.png"),
}

# =====================================================================
# HEADER
# =====================================================================
st.markdown('<div class="main-title">eTraceAI</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">AI-powered Environmental DNA Analysis & Deep-Sea Novelty Detection</div>',
    unsafe_allow_html=True,
)
st.markdown("<hr>", unsafe_allow_html=True)

# =====================================================================
# HOME TAB
# =====================================================================
if page == "Home":

    st.markdown('<div class="section-title">Upload FASTA</div>', unsafe_allow_html=True)
    st.markdown('<div class="card">Upload your eDNA FASTA file to begin AI-based classification.</div>',
                unsafe_allow_html=True)

    uploaded_file = st.file_uploader("Select FASTA File", type=["fasta", "fa"])

    if uploaded_file:
        with open(UPLOAD_PATH, "wb") as f:
            f.write(uploaded_file.read())

        st.success("FASTA uploaded successfully.")

        with st.spinner("Running eTraceAI pipeline…"):
            subprocess.run(["python", "app/taxonomy_matcher.py"])
            subprocess.run(["python", "app/cluster.py"])
            subprocess.run(["python", "app/phylum_barplot.py"])

        st.success("Processing complete. Check Results & Visualizations tabs.")

# =====================================================================
# RESULTS TAB
# =====================================================================
elif page == "Results":

    st.markdown('<div class="section-title">Taxonomic Match Results</div>', unsafe_allow_html=True)

    if os.path.exists(RESULT_CSV):

        df = pd.read_csv(RESULT_CSV)

        # Ensure all expected model columns exist
        required_cols = [
            "DL_MarineScore", "HybridScore", "NoveltyScore",
            "NoveltyType", "HabitatConsensus", "ConfidenceScore"
        ]
        for col in required_cols:
            if col not in df.columns:
                df[col] = 0.0 if "Score" in col else "Unknown"

        total = len(df)
        n_marine = (df["DL_MarineScore"] > 0.7).sum()
        n_novel = (df["NoveltyScore"] > 0.6).sum()

        c1, c2, c3 = st.columns(3)
        c1.metric("Total sequences", total)
        c2.metric("Marine-like (DL > 0.7)", n_marine)
        c3.metric("Potential novel (Novelty > 0.6)", n_novel)

        st.markdown("### 🔍 Filter Results")

        filter_type = st.radio(
            "Choose filter:",
            [
                "Show All",
                "Novel Sequences (NoveltyScore > 0.6)",
                "High-Confidence Marine (DL_MarineScore > 0.7)",
                "High-Confidence Non-Marine (DL_MarineScore < 0.3)",
                "Ambiguous (0.3–0.7 Marine Probability)",
            ],
            horizontal=True,
        )

        filtered = df.copy()
        if filter_type == "Novel Sequences (NoveltyScore > 0.6)":
            filtered = df[df["NoveltyScore"] > 0.6]
        elif filter_type == "High-Confidence Marine (DL_MarineScore > 0.7)":
            filtered = df[df["DL_MarineScore"] > 0.7]
        elif filter_type == "High-Confidence Non-Marine (DL_MarineScore < 0.3)":
            filtered = df[df["DL_MarineScore"] < 0.3]
        elif filter_type == "Ambiguous (0.3–0.7 Marine Probability)":
            filtered = df[(df["DL_MarineScore"] >= 0.3) & (df["DL_MarineScore"] <= 0.7)]

        st.write(f"### Showing **{len(filtered)}** sequences")
        st.dataframe(filtered, use_container_width=True)

        st.download_button(
            "Download Filtered CSV",
            data=filtered.to_csv(index=False).encode(),
            file_name="filtered_results.csv",
        )

        # =====================================================
        # TAXONOMY MULTI-LEVEL BARPLOTS (Phylum → Genus)
        # =====================================================
        st.markdown('<div class="section-title">Taxonomy Insights (Phylum → Genus)</div>',
                    unsafe_allow_html=True)

        with st.expander("📊 Show Biodiversity Barplots (All Ranks)"):
            for rank, (total_path, novel_path) in TAXON_IMAGES.items():
                st.markdown(f"### {rank} Distribution")

                cols = st.columns(2)
                if os.path.exists(total_path):
                    cols[0].image(total_path, caption=f"{rank} (All)", use_column_width=True)
                if os.path.exists(novel_path):
                    cols[1].image(novel_path, caption=f"{rank} (Novel Only)", use_column_width=True)

    else:
        st.info("Upload a FASTA file first.")

# =====================================================================
# VISUALIZATION TAB
# =====================================================================
elif page == "Visualizations":

    st.markdown('<div class="section-title">UMAP Cluster Visualization</div>', unsafe_allow_html=True)

    if os.path.exists(EMB_PATH) and os.path.exists(RESULT_CSV):

        df = pd.read_csv(RESULT_CSV)
        embeddings = np.load(EMB_PATH)

        reducer = __import__("umap").UMAP(n_components=2, random_state=42)
        reduced = reducer.fit_transform(embeddings)

        plot_df = pd.DataFrame({
            "x": reduced[:, 0],
            "y": reduced[:, 1],
            "Organism": df["Organism"],
            "DL_MarineScore": df["DL_MarineScore"],
            "NoveltyScore": df["NoveltyScore"],
            "NoveltyType": df["NoveltyType"],
        })

        fig = px.scatter(
            plot_df,
            x="x", y="y",
            color="NoveltyScore",
            hover_data=["Organism", "DL_MarineScore", "NoveltyScore", "NoveltyType"],
            color_continuous_scale="Turbo",
            title="UMAP Projection (DBN Embeddings + Novelty Analysis)",
        )
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("### Potential Novel Sequences")
        novels = plot_df[plot_df["NoveltyScore"] > 0.6]
        if len(novels) > 0:
            st.warning(f"🔍 {len(novels)} potential novel sequences detected")
            st.dataframe(novels)
        else:
            st.success("No strongly novel sequences identified.")

    else:
        st.info("Run analysis first.")

# =====================================================================
# FASTA PREVIEW TAB
# =====================================================================
elif page == "FASTA Preview":
    st.markdown('<div class="section-title">FASTA Preview</div>', unsafe_allow_html=True)

    if os.path.exists(UPLOAD_PATH):
        seqs = list(SeqIO.parse(UPLOAD_PATH, "fasta"))
        st.write(f"Total sequences detected: **{len(seqs)}**")

        for rec in seqs[:5]:
            st.code(f">{rec.id}\n{str(rec.seq)[:300]}...")

    else:
        st.info("Upload FASTA first.")

# =====================================================================
# DEVELOPER TAB
# =====================================================================
elif page == "Developer Info":
    st.markdown("### Team: CRISPR_CREW")
    st.write("Smart India Hackathon – Grand Finale")
    st.write("NIT Raipur")
    st.write("Developer: **Shubham Thakur**")

# =====================================================================
# FOOTER
# =====================================================================
st.markdown(
    '<div class="footer">© eTraceAI | Deep Sea Biodiversity Intelligence Platform</div>',
    unsafe_allow_html=True,
)
